### ISSUE TITLE
Languages are mixed

### ISSUE THREAD

**Issue by michelesbw** [sbwtech/sbw#1]
Here for example (Groups->Create new group https://beta.socialbusinessworld.org/groups/add/8992) I have english set as user and english as main site's language but languages are mixed
![language](https://cloud.githubusercontent.com/assets/5203511/16557557/e6847b6e-41e0-11e6-9562-0ffa09116cca.png)

**Comment by juho-jaakkola** [comment]
For me everything is in English. Please give detailed instructions on how to reproduce.

**Comment by michelesbw** [comment]
Mmm, seems working fine now, let's close this issue, maybe it was a strange cache one?
