### ISSUE TITLE
Donation plugin by Soren Skuttrupp (slyhne) NOW working on Elgg 2?

### ISSUE THREAD

**Issue by michelesbw** [sbwtech/sbw#10]
http://elgg.org/plugins/401957/1.8.3/donation

**Comment by michelesbw** [comment]
From user comment here I see it's working on Elgg 2

**Comment by michelesbw** [comment]
Seems working fine and this should also fix issue #10 in theme

**Comment by juho-jaakkola** [comment]
The plugin has neither a composer package nor a source code repository, so it is impossible to install it with the Corrent way™.

I've [asked](https://elgg.org/plugins/401957/releases/1.10#elgg-object-2547489) him to add the plugin to Github.

**Comment by michelesbw** [comment]
I also asked Soren, let's hope, This is not among blockers btw.

**Comment by michelesbw** [comment]
Plugin seems not maintained anymore...let's forget about it...
