### ISSUE TITLE
Notifications subjects plugin NOW Elgg 2 ready? YES

### ISSUE THREAD

**Issue by michelesbw** [sbwtech/sbw#13]
https://github.com/AU-Landing-Project/Notification-Subjects

**Comment by juho-jaakkola** [comment]
What are the uses cases for this? Elgg core notifications have been enhanced a lot since this plugin was originally make, so maybe it's not necessary anymore.

**Comment by michelesbw** [comment]
Notifications are sent in recipient's language and subjects are not generic but very explanatory (ie. Michele has uploaded a new video titled: "Juho is the best"). Also very highly customizable, see screenshot
![notifications_subjects](https://cloud.githubusercontent.com/assets/5203511/16761489/a7a8672a-4820-11e6-92d5-91ed2d528064.png)

**Comment by michelesbw** [comment]
maybe now it's installable

**Comment by michelesbw** [comment]
Seems not to take effect, notifications' subjects are the default ones. Can't use it then.

**Comment by michelesbw** [comment]
My bad, yes, it works correctly, my previous test was wrong. To install then.

**Comment by michelesbw** [comment]
Not needed anymore, default elgg notifications are ok
