### ISSUE TITLE
[reminder] recreate pads logging in as... because of New Etherpad plugin

### ISSUE THREAD

**Issue by michelesbw** [sbwtech/sbw#2]
Beta currently has the new version: https://github.com/nlybe/Elgg-Etherpad
Production (Elgg 1.9) us using the old version: https://elgg.org/plugins/2204644

We need to find out whether the old plugin could be replaced with the new one.

Potential Elgg field mappings between the new and the old plugin:

| Old | New |
|-----|-----|
|subtype (etherpad)|subtype (etherpad)|
|url|
|objetive|
|owner_guid|
|container_guid|container_guid|
|group_guid|
|access_id|access_id|
|-|write_access_id|
|-|page_guid|
|-|parent_guid|
|-|tags|
|-|pname|

**Comment by juho-jaakkola** [comment]
Has the new plugin been tested with the old data?

**Comment by michelesbw** [comment]
Yep, ie try from https://beta.socialbusinessworld.org/etherpad/all this one https://beta.socialbusinessworld.org/etherpad/view/604435/ and you'll see "Oops no pads..."

**Comment by juho-jaakkola** [comment]
The plugin configuration is wrong in beta . Who knows how to configure it? @feroda?

**Comment by michelesbw** [comment]
Config is veru different between prod and beta so I didn't go ahead, sorry if I didn't mention it before

**Comment by juho-jaakkola** [comment]
Who has configured the etherpad instance and knows the current config, or could modify it to match the required settings at beta?

**Comment by michelesbw** [comment]
Plugin's setting is only "URL base" set on http://pad.befair.it (Luca's server)

**Comment by feroda** [comment]
I have no admin access in beta, cannot be sure if the installed version is the new one, pls give me admin access ;)

**Comment by feroda** [comment]
Ok, I have managed the installation of the new version (https://github.com/nlybe/Elgg-Etherpad) in my Elgg test site, I can debug now why it does not work on beta.

**Comment by feroda** [comment]
guys, I experience a strange problem: in beta.sbw I the etherpad plugin is creating the pad in the right way. It puts also the iframe of the pad in the page, but it is hidden. I have taken a look at the css with DOM inspector and it seems the same as my elgg test site, Furthermore I have also reinstalled the plugin. It is so strange that the iframe is not loaded in the page. Monitoring the network I don't get the request.

I attach my test site pad page with the inspector and the beta.sbw pad page with the inspector.

**My site**
![mytestsite_20160825_163904](https://cloud.githubusercontent.com/assets/232176/17973489/f4a0ce66-6ae2-11e6-90a3-94aa2faf3bd3.png)

**Beta SBW**
![beta_sbw_screenshot_20160825_163943](https://cloud.githubusercontent.com/assets/232176/17973488/f49e4c2c-6ae2-11e6-939f-2e1fbd5e567c.png)

**Comment by juho-jaakkola** [comment]
Beta was trying to load the iframe contents using an insecure connection, which caused it to fail. Now the iframe is visible, but there are other errors.

**Comment by michelesbw** [comment]
Luca why not have pads over https on your server as well or use sbw's? Let's try to avoid insecure connections as much as we can

**Comment by michelesbw** [comment]
I'm sure you've seen it but let's keep it here for reference. Previously created pads, when viewed give the error: Cannot GET /p/?userName=SBW+Team+%28%40admin%29&showControls=true&useMonospaceFont=false&showChat=true&showLineNumbers=true

**Comment by feroda** [comment]
Thanks guys for you feedback. @juho-jaakkola the iframe in http was the weird thing. Thanks.

Etherpad Lite is now installed and configured in the SBW server and behind HTTPS Reverse proxy of the web server. Configured the new plugin and working.

I cannot close the issue until we have a script to migrate old to new pads (or defined a manual procedure to perform when we switch to newer elgg version)

**Comment by juho-jaakkola** [comment]
The old pads do not have titles. I'm wondering whether we should name them "Nameless" or perhaps take an excerpt from the description field.

**Comment by michelesbw** [comment]
I would go for no title and then owners can edit if needed/desired

**Comment by juho-jaakkola** [comment]
I wrote the previous comment before I knew the problems with the other fields...

Production site currently has 28 pads. It however seems like most of them are just tests. I'm inclined to not exporting the old data to the new structure, but instead creating new pads, and copy-pasting contents from the old pads to the new ones. (...and simply ditching the test content)

**Comment by michelesbw** [comment]
Ok so I've removed this from upgrade blockers and changed the title for me to remember about it.

**Comment by michelesbw** [comment]
moved to relevant checklist here https://github.com/sbwtech/sbw/issues/45
