### ISSUE TITLE
Landr plugin for homepage, Elgg 2 ready

### ISSUE THREAD

**Issue by michelesbw** [sbwtech/sbw#22]
https://elgg.org/plugins/1995172

**Comment by juho-jaakkola** [comment]
I've asked Cim to submit the plugin to packagist: https://elgg.org/plugins/1995172/releases/2.0.1#elgg-object-2516794

**Comment by juho-jaakkola** [comment]
Waiting for a PR that will make it installable with Composer: https://github.com/manacim/Landr/pull/1

**Comment by juho-jaakkola** [comment]
Fixed in 903fd1265b6569d41b17871adc468ffe9303a192
