### ISSUE TITLE
River autoupdate missing

### ISSUE THREAD

**Issue by michelesbw** [sbwtech/sbw#23]
When saving a Wall item from activity page it does not get automatically updated. Prod site has this feature either in River addon plugin or current theme I guess, or it's a Wall latest version's bug/removed feature.

**Comment by michelesbw** [comment]
I think we should seriously consider hypelists which seems to also include autoupdate for lists, can we test it on beta?

**Comment by michelesbw** [comment]
If using hypelists let's consider that sidebar could never be reached in mobile phones because it is at the bottom of each page

**Comment by juho-jaakkola** [comment]
> When saving a Wall item from activity page it does not get automatically updated.

Just to be sure: can you describe *what* exactly does not get updated? The original issue doesn't sound like it has anything to do with AJAX pagination (that your more later comments are referring to).

**Comment by michelesbw** [comment]
activity page= /activity
Ref. hypelists "I think we should seriously consider hypelists which seems to also include autoupdate for lists". This plugin maybe has this autoupdate function (activity's being it a list of river items itself) but I'm not sure :)

**Comment by juho-jaakkola** [comment]
I still do not understand what doesn't get updated. The whole page? Or is it that new wall items are posted using AJAX, and the item you post, won't appear in the list until you manually refresh the whole page? So it should fetch the new item during the AJAX request and prepend it to the list without reloading the whole page?

**Comment by michelesbw** [comment]
I guess second case. To be sure technically speaking just post a wall on SBW prod to see what happens (then please delete it :))

**Comment by juho-jaakkola** [comment]
I tested, and the difference is:
 - Old way: Adding a new wall item reloads the whole page, so the new item appears to the list
 - New way: The item is added with XHR (page doesn't get reloaded), but the new item is not prepended to the list

I believe the correct course of action is to make a feature request about prepending the item to the list after successful XHR request.

**Comment by michelesbw** [comment]
@hypeJunction are you ok if we add this as feature request?

**Comment by hypeJunction** [comment]
What exactly?

**Comment by michelesbw** [comment]
>     New way: The item is added with XHR (page doesn't get reloaded), but the new item is not prepended to the list
> 
> I believe the correct course of action is to make a feature request about prepending the item to the list after successful XHR request.

**Comment by hypeJunction** [comment]
I am not going to add it to hypeWall. I am tired of implementing these hacky per action updates. For that to work you know exactly where the form is rendered and which list it iseant to update, which is a guessing game. I have spent weeks polishing hypeLists for that particular reason.

**Comment by michelesbw** [comment]
Ok understood, no questioning of course but I think that users, not being able to immediately see what posted would not refresh the page but post again and again :).
@juho-jaakkola let's keep this open until we find a solution. Cheers

**Comment by hypeJunction** [comment]
Just add hypeLists. It doesn't interfere with other plugins.

**Comment by michelesbw** [comment]
Many versions ago we experienced issues among hypelists and tidypics but I guess they've been solved. Also, our problem now would be having sidebar below main content area in mobile version, if I'm not wrong, hypelists would interfere with reaching it at the bottom of the page because automatically loading content.

**Comment by hypeJunction** [comment]
There is no infinite scroll.  User has to press a button tooaf the next page.
I believe ura uses tidypics with hypeLists, he hasn't reported any issues.

**Comment by hypeJunction** [comment]
To load* sorry my phone sucks at autocomplete

**Comment by michelesbw** [comment]
:D I'm master of typos with/without autocomplete :D 

So, nice! My guess at the top to use hypelist to solve this was correct! Thank you so much Ismayil!

**Comment by michelesbw** [comment]
Just tried posting a wall status update with hypelists 4.0.4 enabled, no luck, river (https://beta.socialbusinessworld.org/activity) doesn't get updated automatically, wall post not prepended to the page's items.

**Comment by michelesbw** [comment]
Not even river addon solves the issue...and it also does have this feature :S

**Comment by hypeJunction** [comment]
Try toggling the global option in settings.  Might need a special tweak for the river without the global.

**Comment by michelesbw** [comment]
No luck, tried all of them, default, Off and Infinite

**Comment by hypeJunction** [comment]
Hm. Ok. Will peep when I am alive again

**Comment by juho-jaakkola** [comment]
Reopening as the automatic update still doesn't work.

**Comment by hypeJunction** [comment]
Should be fixed in hypeWall 4.4.8

**Comment by michelesbw** [comment]
That would be great! :) I demoted this issue yesterday to upgrade...if solved then very happy :)

**Comment by michelesbw** [comment]
Solved, thanks Ismayil!
