### ISSUE TITLE
Install imagick PHP Image Library 

### ISSUE THREAD

**Issue by michelesbw** [sbwtech/sbw#24]
From Tidypics admin:
"A significantly better image library than GD. Not as common as GD. You may need to ask your system administrator to install this. The server info tab in Tidypics settings will tell you whether it is installed.

ImageMagick command line tools

This requires that the PHP function exec() is available which is often disabled for security reasons. You can find ImageMagick on your server by running "which convert".

Once installed, the plugins just needs the path to ImageMagick commands

**Comment by juho-jaakkola** [comment]
The only image manipulation that is currently being done is image resizing, so there aren't really any benefits of using imagemagics instead.

We can get back to this if we ever have a need for features that are not supported by GD.

**Comment by michelesbw** [comment]
https://www.sitepoint.com/imagick-vs-gd/ I see a good point here on many more supported formats but ok, if you say so Juho, let's close this, thank you for reading and replying
