### ISSUE TITLE
Galli elgg embed missing

### ISSUE THREAD

**Issue by michelesbw** [sbwtech/sbw#3]
https://github.com/ColdTrick/galliElggEmbed

Needed, not yet Elgg 2 compatible

**Comment by juho-jaakkola** [comment]
Requested a new branch: https://github.com/teamwebgalli/galliElggEmbed/issues/2

**Comment by michelesbw** [comment]
Please note that the version in use is a different one https://github.com/ColdTrick/galliElggEmbed

**Comment by juho-jaakkola** [comment]
No, they are the same plugin. Coldtrick's repo is a fork from teamwebgalli repo:

![image](https://cloud.githubusercontent.com/assets/883920/16780591/f8a5c5c8-487f-11e6-9f15-e2450056956c.png)

The original repo currently has a slightly newer version.

**Comment by michelesbw** [comment]
We paid for some mods and upgrades, they forked it and modified some code for us, don't remember now if they then made a new repo or modified the initial fork.

**Comment by juho-jaakkola** [comment]
@jeabakker @jdalsem Do you remember details of the upgrades you made?

**Comment by jdalsem** [comment]
there are various changes made... https://github.com/ColdTrick/galliElggEmbed/commits/master

some related css/js and one feature (to embed only the content and not the full page)

**Comment by jdalsem** [comment]
but i see all was merged into the master branch https://github.com/teamwebgalli/galliElggEmbed/pull/1...
so need to use the fork anymore

**Comment by michelesbw** [comment]
Thank you all for helping out!

**Comment by juho-jaakkola** [comment]
I've upgraded the plugin to be compatible with Elgg 1.9+, and made a PR: https://github.com/teamwebgalli/galliElggEmbed/pull/3

**Comment by michelesbw** [comment]
Great!
