### ISSUE TITLE
Ck Editor Extended video embedding does not work

### ISSUE THREAD

**Issue by michelesbw** [sbwtech/sbw#30]
If trying to add a video through CK Editor Extended ie. in a blog post <iframe width="560" height="315" src="https://www.youtube.com/embed/_pmVEZI_5Fo" frameborder="0" allowfullscreen></iframe> the video is retrieved correctly but when saving it disappears

**Comment by michelesbw** [comment]
Maybe it's not a bug but htmlawed filtering out things so we should use plugin's settings "Configure extra rules for htmlawed to trust specific elements or schemes" to alow ie. youtube, vimeo, metacafé, Prezi, and other common/reliable sources.

**Comment by michelesbw** [comment]
Should we use Ismayil's instead? Seems much better https://github.com/hypeJunction/Elgg-ckeditor_addons

**Comment by juho-jaakkola** [comment]
Yes, it is most likely being removed by htmLawed.

But won't the `<iframe>` part become unnecessary once we get `embed_extender` plugin to work? (Issue #39 suggests that it's currently not working.)

**Comment by michelesbw** [comment]
Embed code doesn't work but simply pasting video link works... Issue #39 has been closed and hopefully users will only copy/paste direct link...

**Comment by michelesbw** [comment]
Works now via hypeembed
