### ISSUE TITLE
BO/FO does not load ckeditor (at least in Chrome)

### ISSUE THREAD

**Issue by michelesbw** [sbwtech/sbw#32]

**Comment by juho-jaakkola** [comment]
There's an error that seems to be originated from ckeditor_extended. CKEditor starts working when it's disabled.

Perhaps some piece of javascript has been deprecated in Elgg 2.2 and this has accidentally broken backwards compatibility. Need to investigate further.

**Comment by juho-jaakkola** [comment]
https://github.com/ColdTrick/ckeditor_extended/issues/9

**Comment by michelesbw** [comment]
Should we replace it with Ismayil's https://github.com/hypeJunction/Elgg-ckeditor_addons ?

**Comment by michelesbw** [comment]
Ismayil's plugin solves this

**Comment by juho-jaakkola** [comment]
Can you list the minimum needs for the editor? Just to know what is required by SBW.

**Comment by michelesbw** [comment]
I would say what now in production.
Pasting here ck.editor extended settings:
toolbar: [['Bold', 'Italic', 'Underline', 'Strike', 'Styles', 'Format', 'RemoveFormat'], ['Source'], ['NumberedList', 'BulletedList', 'Undo', 'Redo', 'Link', 'Unlink', 'Anchor', 'Indent', 'Outdent', 'Table', 'HorizontalRule', 'SpecialChar', 'Blockquote', 'Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', 'Maximize'], ['Image', 'MediaEmbed']],
removeButtons: 'Subscript,Superscript', // To have Underline back
allowedContent: true,
baseHref: elgg.config.wwwroot,
defaultLanguage: 'en',
language: elgg.config.language,
skin: 'moono',
uiColor: '#EEEEEE',
contentsCss: elgg.get_simplecache_url('css', 'elgg/wysiwyg.css'),
disableNativeSpellChecker: false,
disableNativeTableHandles: false,
removeDialogTabs: 'image:advanced;image:Link;link:advanced;link:target',
autoGrow_maxHeight: $(window).height() - 100,
extraPlugins: 'mediaembed',

**Comment by michelesbw** [comment]
See also this related issue for videos embedding https://github.com/sbwtech/sbw/issues/30

**Comment by michelesbw** [comment]
Being due to 3rd party plugin we can consider this not upgrade blocker anymore and hope this issue will be closed either by Coldtrick fixing ckeditor extended or improving performance with Ismayil's enabled.
Extension of ckeditor is much needed for embedding images/videos and also allowing more text formatting capabilities as listed above.

**Comment by michelesbw** [comment]
solved at some point
