### ISSUE TITLE
HypeAttachments not working in entities, comments only

### ISSUE THREAD

**Issue by michelesbw** [sbwtech/sbw#36]
Check HypeAttachments - Invalid https://beta.socialbusinessworld.org/admin/plugins

**Comment by juho-jaakkola** [comment]
Have you checked the plugin settings?

**Comment by juho-jaakkola** [comment]
The bug in fact seems to be that with the current settings it shouldn't work with comments *either*.

**Comment by michelesbw** [comment]
Ok, hypeattachments has now plenty of entities to select from in plugin's settings which is a brand new feature it doesn't have on current production site. My bad if I missed that but had no idea of this big enhancement. Also, we have "Attachments" enabled (a second, different plugin) which is supposed to be a SBW customization. Maybe they now conflict with each other? Should we ask Ismayil?

**Comment by juho-jaakkola** [comment]
Yes, he might have some insight.

**Comment by hypeJunction** [comment]
The seco d attachment plugin extends forms and views for comments, replies and messages, since they don't have entity menus.
I have been doing some more work on attachments today, will be pishing that tomorrow. Mainly relates to javascript changes.
From the issue description, I don't understand the problem.

**Comment by michelesbw** [comment]
I am confused, sorry. I see comments, replies and messages among options to select from in hypeattachments settings. So, is the second plugin sbw_attachments still needed?

**Comment by hypeJunction** [comment]
Yes. hypeAttachments only provides a generic interface. Anything that
doesn't use standard views or menus needs a shim. Those are partially
provided by sbw_attachments. In case you run into other entities that don't
seem to have attachments they will also need to be shimmed. I just don't
want to start supporting all the random plugins in hypeAttachments. Plugins
that adhere to core standards should work fine out of the box.

**Comment by michelesbw** [comment]
Thanks for explaining about these plugins. To my non-dev ears something sounds unexpected though. Aren't comments, messages and replies all standard core features? I'm surely missing something so no worries, if/when you guys have time and will to explain please feel free, no rush at all :)

**Comment by hypeJunction** [comment]
I don't want to incorporate them into the plugin, because I would have to override views, which will inevitably lead to conflicts with other plugins. Plus, I am pushing in some features into 2.3, which will no longer require overriding views to achieve the desired behavior.

**Comment by hypeJunction** [comment]
I have made a new release of hypeAttachments.

**Comment by michelesbw** [comment]
Always grateful for the time spent in replying and explaining!
LOVE

**Comment by michelesbw** [comment]
Ok, seems working just fine after latest upgrade, thank you @hypeJunction !
