### ISSUE TITLE
Groups map missing

### ISSUE THREAD

**Issue by michelesbw** [sbwtech/sbw#4]
Zip file sent to Juho maybe still missing composer.json from Nikos?

**Comment by juho-jaakkola** [comment]
I still haven't uploaded the Groups map plugin to either Bitbucket or Github. I believe the reason was, that the zip package did not contain the git repository for it.

**Comment by michelesbw** [comment]
Just sent the plugin via email

**Comment by juho-jaakkola** [comment]
Fixed in 8e1d57b46751489244de1fff4990c8e49e9a28ea
