### ISSUE TITLE
Event manager by coldtrick not working in various areas (see below)

### ISSUE THREAD

**Issue by michelesbw** [sbwtech/sbw#42]
Event manager coldtrick not working.

- [x] No past events in search results
- [x] no calendar view
- [x] on new event add location search doesn't work
- [x] no map when logged out

**Comment by juho-jaakkola** [comment]
Location search was broken because of the error caused by #32. I disabled ckeditor_extended, and now it works again.

I was able to reprocude the `no calendar view`, but everything else works fine:

![image](https://cloud.githubusercontent.com/assets/883920/17906148/c5f29a46-697e-11e6-9667-8778ff2980d6.png)

**Comment by juho-jaakkola** [comment]
The calendar view is broken because of this bug: https://github.com/ColdTrick/event_manager/issues/85

**Comment by michelesbw** [comment]
Ok, thanks. I now see also "On the map" tab not working when logged out.

**Comment by juho-jaakkola** [comment]
> Ok, thanks. I now see also "On the map" tab not working when logged out.

Try this:
 1. Go to https://beta.socialbusinessworld.org/events
 2. Click "On the map"-tab
 3. Select "Include past events"
 4. Click "Search"-button

Result:

![image](https://cloud.githubusercontent.com/assets/883920/17919956/fe61c6c6-69d9-11e6-95a7-74a84ea338fe.png)

**Comment by michelesbw** [comment]
It's not intended to work only with past events or after searching. I just posted a new event but it's not on the map (only when logged out)

**Comment by juho-jaakkola** [comment]
I was assuming that there's only past events, because the data at beta is quite old.

This should be reported as a bug to event_manager.

**Comment by michelesbw** [comment]
Ok done here https://github.com/ColdTrick/event_manager/issues/86

**Comment by michelesbw** [comment]
Ok all working well now after latest upgrade, thanks @juho-jaakkola @ColdTrick !
