### ISSUE TITLE
Sending messages does not work

### ISSUE THREAD

**Issue by michelesbw** [sbwtech/sbw#46]
Tried to send a message to Michele via Hover menu's "Send a message" link but when correctly opened the link /messages/compose?send_to=8992 the "To" field was empty (first problem) and even if adding it manually, error on "Send", see screenshots below
![message2](https://cloud.githubusercontent.com/assets/5203511/18471750/a34fb4de-79b3-11e6-9c2f-b2bffb603ab6.png)
![message1](https://cloud.githubusercontent.com/assets/5203511/18471751/a354d1f8-79b3-11e6-89f4-eadd38cc962b.png)

**Comment by michelesbw** [comment]
@hypeJunction looks like Tokeninput (v 4.1.0) is the culprit :). After disabling it messages worked fine.

**Comment by hypeJunction** [comment]
Update to latest. It was fixed in 4.1.1 https://github.com/hypeJunction/elgg_tokeninput/blob/master/CHANGELOG.md

**Comment by michelesbw** [comment]
Huh? Thanks! We launched a composer update yesterday...maybe wrong repo?
Cheers!

**Comment by hypeJunction** [comment]
I don't see it in composer dependencies, so it must have resolved to a wrong version from one of the other plugins. I think adding it to composer with a `~4.1` constraint will be safe.

**Comment by michelesbw** [comment]
Yep, it's on our server's composer.lock being it a dependency for Granular Access and locked to 4.1.0 :)
Thanks a lot!

**Comment by juho-jaakkola** [comment]
PR for granular_access waiting to be reviewed: https://github.com/beck24/granular_access/pull/10

**Comment by juho-jaakkola** [comment]
Should be fixed now that we're using version `4.1.2` of elgg_tokeninput.

**Comment by michelesbw** [comment]
It does work! Unfortunately neither my "fix" to remove logo nor html formatting works in notifications sent :S.
