### ISSUE TITLE
Videolist plugin needs upgrade to Elgg 2, available on Github

### ISSUE THREAD

**Issue by michelesbw** [sbwtech/sbw#5]
https://github.com/propertunist/videolist

**Comment by juho-jaakkola** [comment]
Are there some features that are actually broken in Elgg 2?

**Comment by juho-jaakkola** [comment]
I updated it both for Elgg 1.9 and 2.0 today.

**Comment by michelesbw** [comment]
Great Juho! Seems to work fine!
