### ISSUE TITLE
Scheduling columns seem misplaced by 1 (see screensshot)

### ISSUE THREAD

**Issue by michelesbw** [sbwtech/sbw#60]
It seems that 1st column is shifted to right.
<img width="575" alt="screenshot-socialbusinessworld org 2016-11-09 10-41-25" src="https://cloud.githubusercontent.com/assets/5203511/20167662/23ed09e8-a71d-11e6-9db6-5248f929f94c.png">

**Comment by juho-jaakkola** [comment]
This is caused by the Elggx Badges plugin. It seems to do something funny with the user icon: https://github.com/iionly/elggx_badges/blob/master/views/default/icon/user/default.php#L82

**Comment by iionly** [comment]
Elgg version used? There were changes in views/default/icon/user/default.php introduced in Elgg 2.2 (usage of icon service). Elggx Badges overrides the icon view but I have not made a new release for Elgg >= 2.2 specifically as I hadn't noticed any issues so far. So, is the issue showing up on Elgg 2.2 or already on an older version of Elgg?

If there is an issue showing up, the change introduced in Elgg 2.2 is probably not fully BC. Bummer!! Though I don't know why the line you referrenced, @juho-jaakkola, should cause the issue as it's also still in the original icon view of Elgg 2.2.

**Comment by juho-jaakkola** [comment]
I jumped into conclusion too quickly. The problem is in fact caused by the `<td>` tags used within the view: https://github.com/iionly/elggx_badges/blob/master/views/default/icon/user/default.php#L72

**Comment by juho-jaakkola** [comment]
I added an issue here: https://github.com/iionly/elggx_badges/issues/2

**Comment by juho-jaakkola** [comment]
Fixed to a temporary branch in bcbf32278fb8be5997e6ff1f74cc9d13be656095

**Comment by iionly** [comment]
@juho-jaakkola I've made new releases including your fix.
