### ISSUE TITLE
Unexpected error when clicking on like on all objects types

### ISSUE THREAD

**Issue by michelesbw** [sbwtech/sbw#67]
Error thrown: "Unexpected error while performing an AJAX call. Maybe the connection to the server is lost."
Users get obviously disappointed.

**Comment by juho-jaakkola** [comment]
This is caused by the campaigns plugin.

Pending fix can be found here: https://github.com/sbwtech/sbw_campaigns/pull/2

**Comment by michelesbw** [comment]
Ok solved, thanks @juho-jaakkola @hypeJunction !
