### ISSUE TITLE
Vroom plugin not yet Elgg 2 compatible, dependency for Granular access

### ISSUE THREAD

**Issue by michelesbw** [sbwtech/sbw#8]
https://github.com/jumbojett/vroom

**Comment by juho-jaakkola** [comment]
What parts of it are incompatible?

**Comment by michelesbw** [comment]
Mmm, sorry for maybe bad statement but since I read Elgg 1.8 in manifest, I suppose it's a very old plugin possibly causing issues.

**Comment by juho-jaakkola** [comment]
I checked the code, and there doesn't seem to by anything incompatible with Elgg 2.
